Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2024
Var
contador : inteiro


Inicio
contador <- 1
Enquanto (contador <= 100) faca
se (contador % 10 = 0) entao
  escreval(contador, " É multiplo de 10")
  senao
  escreval(contador)
  Fimse


contador <- contador + 1
FimEnquanto


Fimalgoritmo